import type { ComponentProps } from "react";
import {
  Activity,
  AudioLines,
  ArchiveRestore,
  ArrowLeft,
  ArrowUp,
  Blocks,
  ChevronDown,
  ChevronRight,
  CirclePause,
  Copy,
  Cpu,
  Database,
  Ellipsis,
  File,
  FileText,
  Focus,
  Folder,
  Funnel,
  GalleryVerticalEnd,
  Globe,
  House,
  Image,
  Link,
  ListTree,
  LoaderCircle,
  Mail,
  Network,
  Package,
  Palette,
  PanelLeft,
  Pencil,
  Pin,
  Play,
  Plus,
  Presentation,
  Search,
  Settings,
  Sheet,
  ShieldCheck,
  ThumbsDown,
  ThumbsUp,
  Trash2,
  TreePine,
  Wrench,
  X,
  ZoomIn,
  ZoomOut,
  type LucideIcon
} from "lucide-react";

const icons = {
  activity: Activity,
  arrowLeft: ArrowLeft,
  attach: Plus,
  close: X,
  collapse: ChevronDown,
  copy: Copy,
  database: Database,
  edit: Pencil,
  expand: ChevronRight,
  file: File,
  fileText: FileText,
  filter: Funnel,
  fit: Focus,
  folder: Folder,
  globe: Globe,
  home: House,
  image: Image,
  knowledge: TreePine,
  link: Link,
  listTree: ListTree,
  loading: LoaderCircle,
  mail: Mail,
  memory: GalleryVerticalEnd,
  model: Cpu,
  more: Ellipsis,
  network: Network,
  package: Package,
  palette: Palette,
  panel: PanelLeft,
  pause: CirclePause,
  pin: Pin,
  play: Play,
  presentation: Presentation,
  restore: ArchiveRestore,
  search: Search,
  send: ArrowUp,
  settings: Settings,
  shield: ShieldCheck,
  skill: Blocks,
  spreadsheet: Sheet,
  thumbsDown: ThumbsDown,
  thumbsUp: ThumbsUp,
  trash: Trash2,
  voice: AudioLines,
  wrench: Wrench,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut
} satisfies Record<string, LucideIcon>;

export type PigeIconName = keyof typeof icons;

interface PigeIconProps extends Omit<ComponentProps<LucideIcon>, "name"> {
  readonly name: PigeIconName;
}

export function PigeIcon({ name, size = 18, strokeWidth = 1.65, ...props }: PigeIconProps): React.JSX.Element {
  const Icon = icons[name];
  return <Icon aria-hidden="true" focusable="false" size={size} strokeWidth={strokeWidth} {...props} />;
}
